
language: cpp
sudo: false

matrix:

  include:

    - os: osx
      osx_image: xcode8
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Debug' CPP11=1

    # - os: osx
    #   osx_image: xcode8
    #   compiler: clang
    #   env: COMPILER='clang++' BUILD_TYPE='Release' CPP11=1

before_install:
    brew tap homebrew/science
    brew tap fish2000/praxa
    brew update
    brew install libevent pkg-config libunwind-headers
    brew install libffi zlib szip xz snappy lz4
    brew install autoconf automake libtool gflags
    brew install curl gfortran open-mpi boost jemalloc
    brew install jpeg openjpeg jasper libpng libtiff lcms lcms2 giflib gifsicle webp
    brew install cmake python boost-python
    brew install cython doxygen
    brew install libplist yaml-cpp
    brew install hdf5 --c++11 --with-mpi
    brew install llvm
    # pip install -U numpy pythonpy clint wheel
    pip install -U docopt PyYAML iod-symbolize
    brew install fish2000/halide

install:
    brew install fish2000/libimread