
#ifndef IMREAD_TESTDATA_HPP_
#define IMREAD_TESTDATA_HPP_

///
/// test_data.hpp
///
/// ***************** DO NOT EDIT THIS FILE !!! *********************
/// *************** IT WAS AUTOMATICALLY GENERATED ******************
/// *************** CMAKE MAY BLOW IT AWAY AT WILL ******************
///
///
/// Created by scan-test-data.py
/// ... which in turn was created by Alexander Bohn
/// (c) 2015 Objects In Space And Time LLC
/// Some rights are like totally reserved for reals
///

#include <string>

namespace im { namespace test {
    
    static const std::string basedir = "/Users/fish/Dropbox/libimread/tests/data";
    
    static const int num_jpg = 46;
    static const std::string jpg[] = {
        "10350540_10152447396343587_37416966729730477_n.jpg",
        "10954288_342637995941364_1354507656_n.jpg",
        "1a08b088d-2163-470e-aa18-1b0ad1d37298.jpg",
        "1a199abf5-64ff-4582-b68f-47118589250c.2.jpg",
        "1a48fc3ce-be47-4d81-beba-e147ca9083d4.jpg",
        "1a6e4d1dd-f75d-4fbe-be8e-7e50aa23ab9a.jpg",
        "1a95f1603-8937-4e83-9cfb-2e1bc463afb3.2.jpg",
        "1a98f95cf-6005-4d8b-881c-9c44f5648350.jpg",
        "1acad38a0-747f-485b-a6e5-4c02cca8f804.jpg",
        "1aef1426f-848d-455f-8ea5-c143c7eb5139.jpg",
        "1b031bc60-e67d-4904-92da-433b1057ed29.jpg",
        "1b4ca8c13-288f-43ab-8ebb-dc0f00196cb9.2.jpg",
        "1b74c6b88-9b36-43ae-a2ee-dc4ca29cddf2.2.jpg",
        "1b7eefeff-2cb5-401e-b344-0a89ff47f0b7.jpg",
        "2340367304_19afc284dd_o.jpg",
        "4592101968_4fd8106161_o-SMALL.jpg",
        "4592101968_4fd8106161_o-SMALLER.jpg",
        "4592101968_4fd8106161_o-SMALLEST.jpg",
        "5716535667_6e38bef86a_o.jpg",
        "58157_450715217350_41528_n.jpg",
        "7655660314_5633d8d261_o.jpg",
        "7ef12cd7f6ef544d4cfcf9e1e51c8ed2.jpg",
        "8141435491_a3016aca8f_o.jpg",
        "8410078919_6ef8bbbe81_o.jpg",
        "benatar002.jpg",
        "butterflies-in-stomach.jpg",
        "c64error.jpg",
        "CBS-FOX-VIDEO.jpg",
        "columbia-tristar-monochromatic.jpg",
        "CUBE-MY-BUTTON.jpg",
        "Cube_Quest_-_1983_-_Simutrek.jpg",
        "cube_quest_arcade.jpg",
        "Destruct_sequence_engaged.jpg",
        "DIET-PEPSI-UH-HUH-EXCLAMAITION-MARK.jpg",
        "environ-ctr-PURGE.jpg",
        "GLOVE-OF-NINTENDO-POWER-PLUS-ONE.jpg",
        "HANG-IN-THERE.jpg",
        "hang_in_there_baby_by_bytor137-d5u6r1q.jpg",
        "hqdefault.jpg",
        "IMG_4332.jpg",
        "keep-your-power-gloves-off-her-OK.jpg",
        "operation-operation.jpg",
        "Rd4lKZq.jpg",
        "tumblr_l2l22khbRq1qc2qvmo1_1280.jpg",
        "tumblr_mgq73sTl6z1qb9r7fo1_r1_500.jpg",
        "Z0064246.jpg"
    };
    
    static const int num_jpeg = 3;
    static const std::string jpeg[] = {
        "IMG_7333.jpeg",
        "tara-bruno-NO-YOU-DONT-SEE-ME-almost-two-years-ago.jpeg",
        "taylor-omg.jpeg"
    };
    
    static const int num_png = 20;
    static const std::string png[] = {
        "atkinson-me.png",
        "BINARY-OP.png",
        "crypto343343.png",
        "grad_32_rrt_srgb.png",
        "marci_512_srgb.png",
        "marci_512_srgb8.png",
        "output_00100.png",
        "output_00200.png",
        "output_00300.png",
        "output_00400.png",
        "output_00500.png",
        "output_00600.png",
        "output_00700.png",
        "output_00800.png",
        "output_00900.png",
        "pngreference.png",
        "roses_512_rrt_srgb.png",
        "st-in-parens.png",
        "yo-dogg-bleah.png",
        "yo-dogg-OHHH-DOGGGG.png"
    };
    
    static const int num_tif = 1;
    static const std::string tif[] = {
        "ptlobos.tif"
    };
    
    static const int num_tiff = 0;
    static const std::string tiff[] = {

    };
    
    static const int num_hdf5 = 0;
    static const std::string hdf5[] = {

    };
    
    static const int num_pvr = 11;
    static const std::string pvr[] = {
        "AI88.pvr",
        "apple_2bpp.pvr",
        "apple_4bpp.pvr",
        "I8.pvr",
        "pvrtc2bpp.pvr",
        "pvrtc4bpp.pvr",
        "RGB565.pvr",
        "RGB888.pvr",
        "RGBA4444.pvr",
        "RGBA5551.pvr",
        "RGBA8888.pvr"
    };
    
} } /// namespaces

#endif /// IMREAD_TESTDATA_HPP_

