
#ifndef IMREAD_TESTDATA_HPP_
#define IMREAD_TESTDATA_HPP_

///
/// test_data.hpp
///
/// ***************** DO NOT EDIT THIS FILE !!! *********************
/// *************** IT WAS AUTOMATICALLY GENERATED ******************
/// *************** CMAKE MAY BLOW IT AWAY AT WILL ******************
///
///
/// Created by scan-test-data.py
/// ... which in turn was created by Alexander Bohn
/// (c) 2015 Objects In Space And Time LLC
/// Some rights are like totally reserved for reals
///

#include <string>

namespace im { namespace test {
    
    static const std::string basedir = "/Users/fish/Dropbox/libimread/tests/data";
    
    static const int num_jpg = 51;
    static const std::string jpg[] = {
        "10350540_10152447396343587_37416966729730477_n.jpg",
        "10632004_1534049053478864_274950921_n.jpg",
        "10784794_626214094153760_1682042407_n.jpg",
        "10954288_342637995941364_1354507656_n.jpg",
        "11267697_435543873289573_208622370_n.jpg",
        "13694753_189263628155625_1457060035_n.jpg",
        "14145460_1101980163221760_1805788797_n.jpg",
        "14712002_926002110863805_7214626870581526528_n.jpg",
        "15826032_10211365161872908_3691842715293840053_n.jpg",
        "16906646_1858944137716393_6865305734310002688_n.jpg",
        "17932228_1840427066220690_4734820359981760512_n-2.jpg",
        "2340367304_19afc284dd_o.jpg",
        "270642616_21cb3acfb7_o.jpg",
        "4592101968_4fd8106161_o-SMALL.jpg",
        "4592101968_4fd8106161_o-SMALLER.jpg",
        "4592101968_4fd8106161_o-SMALLEST.jpg",
        "5716535667_6e38bef86a_o.jpg",
        "58157_450715217350_41528_n.jpg",
        "7655660314_5633d8d261_o.jpg",
        "7ef12cd7f6ef544d4cfcf9e1e51c8ed2.jpg",
        "8141435491_a3016aca8f_o.jpg",
        "8410078919_6ef8bbbe81_o.jpg",
        "benatar002.jpg",
        "butterflies-in-stomach.jpg",
        "c64error.jpg",
        "CBS-FOX-VIDEO.jpg",
        "cheese.jpg",
        "columbia-tristar-monochromatic.jpg",
        "CUBE-MY-BUTTON.jpg",
        "Cube_Quest_-_1983_-_Simutrek.jpg",
        "cube_quest_arcade.jpg",
        "cx-6288-013.jpg",
        "cx-6636-002.jpg",
        "Destruct_sequence_engaged.jpg",
        "DIET-PEPSI-UH-HUH-EXCLAMAITION-MARK.jpg",
        "DROWNED-CAT-IS-VERY-UPSET.jpg",
        "environ-ctr-PURGE.jpg",
        "forth_on_the_atari.jpg",
        "GLOVE-OF-NINTENDO-POWER-PLUS-ONE.jpg",
        "HANG-IN-THERE.jpg",
        "hang_in_there_baby_by_bytor137-d5u6r1q.jpg",
        "hqdefault.jpg",
        "IMG_4332.jpg",
        "keep-your-power-gloves-off-her-OK.jpg",
        "operation-operation.jpg",
        "Rd4lKZq.jpg",
        "sneakers-passport-100066366-large-6c.jpg",
        "TA-640x353.jpg",
        "tumblr_l2l22khbRq1qc2qvmo1_1280.jpg",
        "tumblr_mgq73sTl6z1qb9r7fo1_r1_500.jpg",
        "Z0064246.jpg"
    };
    
    static const int num_jpeg = 4;
    static const std::string jpeg[] = {
        "378969.jpeg",
        "IMG_7333.jpeg",
        "tara-bruno-NO-YOU-DONT-SEE-ME-almost-two-years-ago.jpeg",
        "taylor-omg.jpeg"
    };
    
    static const int num_png = 20;
    static const std::string png[] = {
        "atkinson-me.png",
        "BINARY-OP.png",
        "crypto343343.png",
        "grad_32_rrt_srgb.png",
        "marci_512_srgb.png",
        "marci_512_srgb8.png",
        "output_00100.png",
        "output_00200.png",
        "output_00300.png",
        "output_00400.png",
        "output_00500.png",
        "output_00600.png",
        "output_00700.png",
        "output_00800.png",
        "output_00900.png",
        "pngreference.png",
        "roses_512_rrt_srgb.png",
        "st-in-parens.png",
        "yo-dogg-bleah.png",
        "yo-dogg-OHHH-DOGGGG.png"
    };
    
    static const int num_tif = 11;
    static const std::string tif[] = {
        "g8960_ct000508.tif",
        "lena_g4_500.tif",
        "LOGO_SCAN.tif",
        "ptlobos.tif",
        "re_g8960_ct000508.tif",
        "re_lena_g4_500_grayscale.tif",
        "re_lena_g4_500_sRGB.tif",
        "re_LOGO_SCAN_flat.tif",
        "re_LOGO_SCAN_psdlayers.tif",
        "re_ptlobos.tif",
        "re_visuallyinterestingtype.tif"
    };
    
    static const int num_tiff = 1;
    static const std::string tiff[] = {
        "visuallyinterestingtype.tiff"
    };
    
    static const int num_hdf5 = 0;
    static const std::string hdf5[] = {

    };
    
    static const int num_pvr = 11;
    static const std::string pvr[] = {
        "AI88.pvr",
        "apple_2bpp.pvr",
        "apple_4bpp.pvr",
        "I8.pvr",
        "pvrtc2bpp.pvr",
        "pvrtc4bpp.pvr",
        "RGB565.pvr",
        "RGB888.pvr",
        "RGBA4444.pvr",
        "RGBA5551.pvr",
        "RGBA8888.pvr"
    };
    
} } /// namespaces

#endif /// IMREAD_TESTDATA_HPP_

