
#ifndef IMREAD_TESTDATA_HPP_
#define IMREAD_TESTDATA_HPP_

///
/// test_data.hpp
///
/// ***************** DO NOT EDIT THIS FILE !!! *********************
/// *************** IT WAS AUTOMATICALLY GENERATED ******************
/// *************** CMAKE MAY BLOW IT AWAY AT WILL ******************
///
///
/// Created by scan-test-data.py
/// ... which in turn was created by Alexander Bohn
/// (c) 2015 Objects In Space And Time LLC
/// Some rights are like totally reserved for reals
///

#include <string>

namespace im { namespace test {
    
    static const std::string basedir = "/Users/fish/Dropbox/libimread/tests/data";
    
    static const int num_jpg = 9;
    static const std::string jpg[] = {
        "10350540_10152447396343587_37416966729730477_n.jpg",
        "10954288_342637995941364_1354507656_n.jpg",
        "c64error.jpg",
        "HANG-IN-THERE.jpg",
        "hang_in_there_baby_by_bytor137-d5u6r1q.jpg",
        "IMG_4332.jpg",
        "keep-your-power-gloves-off-her-OK.jpg",
        "Rd4lKZq.jpg",
        "tumblr_mgq73sTl6z1qb9r7fo1_r1_500.jpg"
    };
    
    static const int num_jpeg = 3;
    static const std::string jpeg[] = {
        "IMG_7333.jpeg",
        "tara-bruno-NO-YOU-DONT-SEE-ME-almost-two-years-ago.jpeg",
        "taylor-omg.jpeg"
    };
    
    static const int num_png = 15;
    static const std::string png[] = {
        "atkinson-me.png",
        "BINARY-OP.png",
        "grad_32_rrt_srgb.png",
        "marci_512_srgb.png",
        "marci_512_srgb8.png",
        "output_00100.png",
        "output_00200.png",
        "output_00300.png",
        "output_00400.png",
        "output_00500.png",
        "output_00600.png",
        "output_00700.png",
        "output_00800.png",
        "output_00900.png",
        "roses_512_rrt_srgb.png"
    };
    
    static const int num_tif = 1;
    static const std::string tif[] = {
        "ptlobos.tif"
    };
    
    static const int num_tiff = 0;
    static const std::string tiff[] = {

    };
    
    static const int num_hdf5 = 0;
    static const std::string hdf5[] = {

    };
    
} } /// namespaces

#endif /// IMREAD_TESTDATA_HPP_

