# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-06-30 03:40
from __future__ import unicode_literals

from django.db import migrations
import im.django.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thingy',
            name='image',
            field=im.django.modelfields.ImageField(height_field='h', max_length=255, null=True, upload_to='uploads/', verbose_name='Image', width_field='w'),
        ),
    ]
