// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: numpy.capnp

#ifndef CAPNP_INCLUDED_a4ff3451b6f64e62_
#define CAPNP_INCLUDED_a4ff3451b6f64e62_

#include <capnp/generated-header-support.h>

#if CAPNP_VERSION != 5003
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(9d4a7b0059734d02);
enum class NumpyTypes_9d4a7b0059734d02: uint16_t {
  NPY_B_O_O_L,
  NPY_B_Y_T_E,
  NPY_U_B_Y_T_E,
  NPY_S_H_O_R_T,
  NPY_U_S_H_O_R_T,
  NPY_L_O_N_G,
  NPY_U_L_O_N_G,
  NPY_L_O_N_G_L_O_N_G,
  NPY_U_L_O_N_G_L_O_N_G,
  NPY_F_L_O_A_T,
  NPY_D_O_U_B_L_E,
  NPY_L_O_N_G_D_O_U_B_L_E,
  NPY_C_F_L_O_A_T,
  NPY_C_D_O_U_B_L_E,
  NPY_C_L_O_N_G_D_O_U_B_L_E,
  NPY_DUMMY0,
  NPY_DUMMY1,
  NPY_O_B_J_E_C_T,
  NPY_S_T_R_I_N_G,
  NPY_U_N_I_C_O_D_E,
  NPY_V_O_I_D,
  NPY_D_A_T_E_T_I_M_E,
  NPY_T_I_M_E_D_E_L_T_A,
  NPY_H_A_L_F,
  NPY_N_T_Y_P_E_S,
  NPY_N_O_T_Y_P_E,
  NPY_C_H_A_R,
  NPY_U_S_E_R_D_E_F,
  NPY_NTYPES_A_B_I_COMPATIBLE,
};
CAPNP_DECLARE_ENUM(NumpyTypes, 9d4a7b0059734d02);

}  // namespace schemas
}  // namespace capnp


typedef ::capnp::schemas::NumpyTypes_9d4a7b0059734d02 NumpyTypes;

// =======================================================================================

// =======================================================================================


#endif  // CAPNP_INCLUDED_a4ff3451b6f64e62_
