language: cpp

matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'boost-latest']
        packages: ['g++-6', 'libboost1.54-dev']
    env: COMPILER=g++-6
  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8', 'boost-latest']
        packages: ['g++-5', 'clang-3.8', 'libboost1.54-dev']
    env: COMPILER=clang++-3.8
  - os: osx
    osx_image: xcode7.3
    compiler: clang
    env: COMPILER=clang++

script:
- export CXX=${COMPILER}
- ${CXX} --version
- mkdir -p build && cd build
- cmake .. && make -j4
- cd tests
- ctest --output-on-failure
