# CMake generated Testfile for 
# Source directory: /Users/fish/Dropbox/libimread
# Build directory: /Users/fish/Dropbox/libimread/xcode/fmwk
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(appkit-copy-paste "./build/imread_tests" "*appkit-copy-paste*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(appkit-copy-paste PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(appkit-copy-paste "./build/imread_tests" "*appkit-copy-paste*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(appkit-copy-paste PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(appkit-copy-paste "./build/imread_tests" "*appkit-copy-paste*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(appkit-copy-paste PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(appkit-copy-paste "./build/imread_tests" "*appkit-copy-paste*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(appkit-copy-paste PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(appkit-copy-paste NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(apple-io "./build/imread_tests" "*apple-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(apple-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(apple-io "./build/imread_tests" "*apple-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(apple-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(apple-io "./build/imread_tests" "*apple-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(apple-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(apple-io "./build/imread_tests" "*apple-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(apple-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(apple-io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(blockhash "./build/imread_tests" "*blockhash*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(blockhash PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(blockhash "./build/imread_tests" "*blockhash*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(blockhash PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(blockhash "./build/imread_tests" "*blockhash*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(blockhash PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(blockhash "./build/imread_tests" "*blockhash*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(blockhash PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(blockhash NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(filesystem "./build/imread_tests" "*filesystem*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(filesystem PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(filesystem "./build/imread_tests" "*filesystem*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(filesystem PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(filesystem "./build/imread_tests" "*filesystem*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(filesystem PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(filesystem "./build/imread_tests" "*filesystem*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(filesystem PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(filesystem NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(gif-write "./build/imread_tests" "*gif-write*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(gif-write PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(gif-write "./build/imread_tests" "*gif-write*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(gif-write PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(gif-write "./build/imread_tests" "*gif-write*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(gif-write PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(gif-write "./build/imread_tests" "*gif-write*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(gif-write PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(gif-write NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(halide-io "./build/imread_tests" "*halide-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(halide-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(halide-io "./build/imread_tests" "*halide-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(halide-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(halide-io "./build/imread_tests" "*halide-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(halide-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(halide-io "./build/imread_tests" "*halide-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(halide-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(halide-io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(hdf5-io "./build/imread_tests" "*hdf5-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(hdf5-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(hdf5-io "./build/imread_tests" "*hdf5-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(hdf5-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(hdf5-io "./build/imread_tests" "*hdf5-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(hdf5-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(hdf5-io "./build/imread_tests" "*hdf5-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(hdf5-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(hdf5-io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(json-block-traverse "./build/imread_tests" "*json-block-traverse*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(json-block-traverse PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(json-block-traverse "./build/imread_tests" "*json-block-traverse*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(json-block-traverse PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(json-block-traverse "./build/imread_tests" "*json-block-traverse*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(json-block-traverse PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(json-block-traverse "./build/imread_tests" "*json-block-traverse*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(json-block-traverse PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(json-block-traverse NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(libguid "./build/imread_tests" "*libguid*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libguid PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(libguid "./build/imread_tests" "*libguid*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libguid PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(libguid "./build/imread_tests" "*libguid*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libguid PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(libguid "./build/imread_tests" "*libguid*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libguid PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(libguid NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(nsdictionary-options-map "./build/imread_tests" "*nsdictionary-options-map*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsdictionary-options-map PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(nsdictionary-options-map "./build/imread_tests" "*nsdictionary-options-map*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsdictionary-options-map PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(nsdictionary-options-map "./build/imread_tests" "*nsdictionary-options-map*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsdictionary-options-map PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(nsdictionary-options-map "./build/imread_tests" "*nsdictionary-options-map*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsdictionary-options-map PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(nsdictionary-options-map NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(nsurl-image-types "./build/imread_tests" "*nsurl-image-types*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsurl-image-types PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(nsurl-image-types "./build/imread_tests" "*nsurl-image-types*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsurl-image-types PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(nsurl-image-types "./build/imread_tests" "*nsurl-image-types*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsurl-image-types PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(nsurl-image-types "./build/imread_tests" "*nsurl-image-types*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(nsurl-image-types PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(nsurl-image-types NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(objc-rt "./build/imread_tests" "*objc-rt*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(objc-rt PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(objc-rt "./build/imread_tests" "*objc-rt*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(objc-rt PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(objc-rt "./build/imread_tests" "*objc-rt*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(objc-rt PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(objc-rt "./build/imread_tests" "*objc-rt*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(objc-rt PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(objc-rt NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(sfinae "./build/imread_tests" "*sfinae*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(sfinae PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(sfinae "./build/imread_tests" "*sfinae*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(sfinae PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(sfinae "./build/imread_tests" "*sfinae*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(sfinae PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(sfinae "./build/imread_tests" "*sfinae*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(sfinae PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(sfinae NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(libsszip "./build/imread_tests" "*libsszip*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libsszip PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(libsszip "./build/imread_tests" "*libsszip*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libsszip PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(libsszip "./build/imread_tests" "*libsszip*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libsszip PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(libsszip "./build/imread_tests" "*libsszip*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(libsszip PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(libsszip NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(terminator "./build/imread_tests" "*terminator*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(terminator PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(terminator "./build/imread_tests" "*terminator*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(terminator PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(terminator "./build/imread_tests" "*terminator*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(terminator PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(terminator "./build/imread_tests" "*terminator*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(terminator PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(terminator NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(interleaved-io "./build/imread_tests" "*interleaved-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(interleaved-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(interleaved-io "./build/imread_tests" "*interleaved-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(interleaved-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(interleaved-io "./build/imread_tests" "*interleaved-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(interleaved-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(interleaved-io "./build/imread_tests" "*interleaved-io*" "--success" "--durations" "yes" "--abortx" "10")
  set_tests_properties(interleaved-io PROPERTIES  WORKING_DIRECTORY "/Users/fish/Dropbox/libimread")
else()
  add_test(interleaved-io NOT_AVAILABLE)
endif()
subdirs(deps)
subdirs(apps)
subdirs(tests)
