
///
/// Generated by iod-symbolizer at 2016-01-20T19:21:58.026635
/// iod-symbolizer by Alexander Bohn -- http://github.com/fish2000/iod-symbolizer
/// IOD library by Matthieu Garrigues -- https://github.com/matt-42/iod
///

#include <iod/symbol.hh>


#ifndef IOD_SYMBOL_mimetype
    #define IOD_SYMBOL_mimetype
    iod_define_symbol(mimetype)
#endif


#ifndef IOD_SYMBOL_json_key
    #define IOD_SYMBOL_json_key
    iod_define_symbol(json_key)
#endif


#ifndef IOD_SYMBOL_suffix
    #define IOD_SYMBOL_suffix
    iod_define_symbol(suffix)
#endif


#ifndef IOD_SYMBOL_integral_map
    #define IOD_SYMBOL_integral_map
    iod_define_symbol(integral_map)
#endif


#ifndef IOD_SYMBOL_native_map
    #define IOD_SYMBOL_native_map
    iod_define_symbol(native_map)
#endif


#ifndef IOD_SYMBOL_byteorder_map
    #define IOD_SYMBOL_byteorder_map
    iod_define_symbol(byteorder_map)
#endif


#ifndef IOD_SYMBOL_standard_map
    #define IOD_SYMBOL_standard_map
    iod_define_symbol(standard_map)
#endif


#ifndef IOD_SYMBOL_x_
    #define IOD_SYMBOL_x_
    iod_define_symbol(x_)
#endif


#ifndef IOD_SYMBOL_signature
    #define IOD_SYMBOL_signature
    iod_define_symbol(signature)
#endif


#ifndef IOD_SYMBOL_typecode_literal_map
    #define IOD_SYMBOL_typecode_literal_map
    iod_define_symbol(typecode_literal_map)
#endif


#ifndef IOD_SYMBOL_typecode_character_map
    #define IOD_SYMBOL_typecode_character_map
    iod_define_symbol(typecode_character_map)
#endif


#ifndef IOD_SYMBOL_string_tailmatch
    #define IOD_SYMBOL_string_tailmatch
    iod_define_symbol(string_tailmatch)
#endif


#ifndef IOD_SYMBOL_optional
    #define IOD_SYMBOL_optional
    iod_define_symbol(optional)
#endif


#ifndef IOD_SYMBOL_out
    #define IOD_SYMBOL_out
    iod_define_symbol(out)
#endif

