
///
/// Generated by iod-symbolizer at 2016-10-15T15:40:10.013139
/// iod-symbolizer by Alexander Bohn -- http://github.com/fish2000/iod-symbolizer
/// IOD library by Matthieu Garrigues -- https://github.com/matt-42/iod
///

#ifndef IOD_SYMBOLYZER_OUTPUT_HEADER_TEMPLATE_
#define IOD_SYMBOLYZER_OUTPUT_HEADER_TEMPLATE_

#include <iod/symbol.hh>


#ifndef IOD_SYMBOL_byteorder
    #define IOD_SYMBOL_byteorder
    iod_define_symbol(byteorder)
#endif


#ifndef IOD_SYMBOL_byteorder_map
    #define IOD_SYMBOL_byteorder_map
    iod_define_symbol(byteorder_map)
#endif


#ifndef IOD_SYMBOL_byteordermark
    #define IOD_SYMBOL_byteordermark
    iod_define_symbol(byteordermark)
#endif


#ifndef IOD_SYMBOL_bytes
    #define IOD_SYMBOL_bytes
    iod_define_symbol(bytes)
#endif


#ifndef IOD_SYMBOL_can_read
    #define IOD_SYMBOL_can_read
    iod_define_symbol(can_read)
#endif


#ifndef IOD_SYMBOL_can_read_metadata
    #define IOD_SYMBOL_can_read_metadata
    iod_define_symbol(can_read_metadata)
#endif


#ifndef IOD_SYMBOL_can_read_multi
    #define IOD_SYMBOL_can_read_multi
    iod_define_symbol(can_read_multi)
#endif


#ifndef IOD_SYMBOL_can_write
    #define IOD_SYMBOL_can_write
    iod_define_symbol(can_write)
#endif


#ifndef IOD_SYMBOL_can_write_metadata
    #define IOD_SYMBOL_can_write_metadata
    iod_define_symbol(can_write_metadata)
#endif


#ifndef IOD_SYMBOL_can_write_multi
    #define IOD_SYMBOL_can_write_multi
    iod_define_symbol(can_write_multi)
#endif


#ifndef IOD_SYMBOL_capacity
    #define IOD_SYMBOL_capacity
    iod_define_symbol(capacity)
#endif


#ifndef IOD_SYMBOL_compress
    #define IOD_SYMBOL_compress
    iod_define_symbol(compress)
#endif


#ifndef IOD_SYMBOL_horizontal_predictor
    #define IOD_SYMBOL_horizontal_predictor
    iod_define_symbol(horizontal_predictor)
#endif


#ifndef IOD_SYMBOL_import_array
    #define IOD_SYMBOL_import_array
    iod_define_symbol(import_array)
#endif


#ifndef IOD_SYMBOL_integral_map
    #define IOD_SYMBOL_integral_map
    iod_define_symbol(integral_map)
#endif


#ifndef IOD_SYMBOL_json_key
    #define IOD_SYMBOL_json_key
    iod_define_symbol(json_key)
#endif


#ifndef IOD_SYMBOL_length
    #define IOD_SYMBOL_length
    iod_define_symbol(length)
#endif


#ifndef IOD_SYMBOL_metadata
    #define IOD_SYMBOL_metadata
    iod_define_symbol(metadata)
#endif


#ifndef IOD_SYMBOL_mimetype
    #define IOD_SYMBOL_mimetype
    iod_define_symbol(mimetype)
#endif


#ifndef IOD_SYMBOL_native_map
    #define IOD_SYMBOL_native_map
    iod_define_symbol(native_map)
#endif


#ifndef IOD_SYMBOL_nothing_
    #define IOD_SYMBOL_nothing_
    iod_define_symbol(nothing_)
#endif


#ifndef IOD_SYMBOL_optional
    #define IOD_SYMBOL_optional
    iod_define_symbol(optional)
#endif


#ifndef IOD_SYMBOL_orientation
    #define IOD_SYMBOL_orientation
    iod_define_symbol(orientation)
#endif


#ifndef IOD_SYMBOL_out
    #define IOD_SYMBOL_out
    iod_define_symbol(out)
#endif


#ifndef IOD_SYMBOL_quality
    #define IOD_SYMBOL_quality
    iod_define_symbol(quality)
#endif


#ifndef IOD_SYMBOL_resolution_unit
    #define IOD_SYMBOL_resolution_unit
    iod_define_symbol(resolution_unit)
#endif


#ifndef IOD_SYMBOL_signatures
    #define IOD_SYMBOL_signatures
    iod_define_symbol(signatures)
#endif


#ifndef IOD_SYMBOL_software_signature
    #define IOD_SYMBOL_software_signature
    iod_define_symbol(software_signature)
#endif


#ifndef IOD_SYMBOL_standard_map
    #define IOD_SYMBOL_standard_map
    iod_define_symbol(standard_map)
#endif


#ifndef IOD_SYMBOL_string_tailmatch
    #define IOD_SYMBOL_string_tailmatch
    iod_define_symbol(string_tailmatch)
#endif


#ifndef IOD_SYMBOL_suffixes
    #define IOD_SYMBOL_suffixes
    iod_define_symbol(suffixes)
#endif


#ifndef IOD_SYMBOL_typecode_character_map
    #define IOD_SYMBOL_typecode_character_map
    iod_define_symbol(typecode_character_map)
#endif


#ifndef IOD_SYMBOL_typecode_literal_map
    #define IOD_SYMBOL_typecode_literal_map
    iod_define_symbol(typecode_literal_map)
#endif


#ifndef IOD_SYMBOL_writeopts
    #define IOD_SYMBOL_writeopts
    iod_define_symbol(writeopts)
#endif


#ifndef IOD_SYMBOL_x_resolution
    #define IOD_SYMBOL_x_resolution
    iod_define_symbol(x_resolution)
#endif


#ifndef IOD_SYMBOL_y_resolution
    #define IOD_SYMBOL_y_resolution
    iod_define_symbol(y_resolution)
#endif


#endif /// IOD_SYMBOLYZER_OUTPUT_HEADER_TEMPLATE_
