
///
/// Generated by iod-symbolizer at None
/// iod-symbolizer by Alexander Bohn -- http://github.com/fish2000/iod-symbolizer
/// IOD library by Matthieu Garrigues -- https://github.com/matt-42/iod
///

#include <iod/symbol.hh>


#ifndef IOD_SYMBOL_color_map
    #define IOD_SYMBOL_color_map
    iod_define_symbol(color_map)
#endif


#ifndef IOD_SYMBOL_fd
    #define IOD_SYMBOL_fd
    iod_define_symbol(fd)
#endif


#ifndef IOD_SYMBOL_x_
    #define IOD_SYMBOL_x_
    iod_define_symbol(x_)
#endif


#ifndef IOD_SYMBOL_signature
    #define IOD_SYMBOL_signature
    iod_define_symbol(signature)
#endif

