#!/usr/bin/env python
#
#       generate-test-header.py
#
#       Scan test data folder and write out a header file
#       For, like, tests and stuff
#       (c) 2015 Alexander Bohn, All Rights Reserved
#

from __future__ import print_function
from os import chdir, listdir, getcwd
from os.path import dirname
from filemap import filemapper

datadir = "../data"

include_tpl = u"""
#ifndef IMREAD_TESTDATA_HPP_
#define IMREAD_TESTDATA_HPP_

///
/// test_data.hpp
///
/// ***************** DO NOT EDIT THIS FILE !!! *********************
/// *************** IT WAS AUTOMATICALLY GENERATED ******************
/// *************** CMAKE MAY BLOW IT AWAY AT WILL ******************
///
///
/// Created by scan-test-data.py
/// ... which in turn was created by Alexander Bohn
/// (c) 2015 Objects In Space And Time LLC
/// Some rights are like totally reserved for reals
///

#include <string>

namespace im { namespace test {
    
    static const std::string basedir = "%(basedir)s";
    %(jpg)s
    %(jpeg)s
    %(png)s
    %(tif)s
    %(tiff)s
    %(hdf5)s
    %(pvr)s
    
} } /// namespaces

#endif /// IMREAD_TESTDATA_HPP_
"""

filetype_tpl = u"""
    static const int num_%(filetype)s = %(num)d;
    static const std::string %(filetype)s[] = {
%(filestr)s
    };"""

def include(**kwargs):
    """ Required args:
            basedir:    string, path to base file directory (like duh)
            jpgs:       string, output from filetype() for jpg files
            jpegs:      string, output from filetype() for jpeg files
                                (N.B. jpg != jpeg)
            pngs:       string, output from filetype() for png files
            tifs:       string, output from filetype() for tif files
            tiffs:      string, output from filetype() for tiff files
                                (likely empty)
            hdf5s:      string, output from filetype() for hdf5 files
            pvrs:       string, output from filetype() for pvr files
    """
    return include_tpl % kwargs

def filetype(suffix, files):
    """ Required Args:
            suffix:     string, file suffix (e.g. 'jpg', 'png' etc)
            files:      list, strings of actual file names per suffix
    """
    return filetype_tpl % dict(
        filestr=u",\n".join([u"        \"%s\"" % f for f in files]),
        filetype=suffix,
        num=len(files))

if __name__ == '__main__':
    chdir(dirname(__file__))
    chdir(datadir)
    basedir = getcwd()
    files = listdir(basedir)
    
    filetpls = dict()
    filemap = filemapper(files)
    
    for suffix, filelist in filemap.iteritems():
        filetpls.update({ suffix: filetype(suffix, filelist) })
    filetpls.update({ 'basedir': basedir })
    print(include(**filetpls))
